services:
  postgres_test:
    container_name: postgres_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DATING_DB
    ports:
      - 5433:5432
  postgres_dev:
    container_name: postgres_dev
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DATING_DB
    ports:
      - 5432:5432
  nginx:
    container_name: nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:4000
    volumes:
      - ./backend/src:/app/src
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src