services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DATING_DB
    ports:
      - 5432:5432
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
  # nginx-react:
  #   build:
  #     context: /frontend
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 80:80