services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
  react:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
