services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
  nginx-react:
    build:
      context: /frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80