apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: backend
          image: zirolet/multi-backend
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: JWTSECRET
              value: secret
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: "5432"
            - name: DB_DB
              value: postgres
            - name: NODE_ENV
              value: prod