apiVersion: app/v1
kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        resources:
          limits:
            memory: "256Mi"   # Maximum memory allowed
            cpu: "0.5"         # Maximum CPU cores allowed
          requests:
            memory: "128Mi"   # Initial memory request
            cpu: "0.1"         # Initial CPU cores request
        ports:
        - containerPort: 3000
        env:
        - name: AWS_ACCESS
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: aws-access
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: aws-secret
---
apiVersion: v1
kind: Service

metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # Yes this should be thiry-thousand