apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  aws-access: QUtJQTVGVFpETERQWUdJS01VTVU=
  aws-secret: ai9jYjdjdVB2OXdUY3dhYjRwcGdlaFQyMitGeGo0NytsSllWMlA4ZQ==