apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: tindeggle-ingress
spec:
  rules:
  - host: tindeggle.site
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000