apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: dGluZGVnZ2xl # BASE64_ENCODED_API_KEY
  postgres-password: QW5pbWVfTG92ZXJzX1VXVS5FWEUxMjM= # BASE64_ENCODED_DATABASE_PASSWORD
  postgres-db: REFUSU5HX0RC