apiVersion: app/v1
kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresdb
        image: postgres
        resources:
          limits:
            memory: "256Mi"   # Maximum memory allowed
            cpu: "0.5"         # Maximum CPU cores allowed
          requests:
            memory: "128Mi"   # Initial memory request
            cpu: "0.1"         # Initial CPU cores request
        ports:
        - containerPort: 12345
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
---
apiVersion: v1
kind: Service

metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345