name: Node.js CI with Docker

on:
    push:
        branches:
            - dev
            - main

jobs:
    build-backend:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
            path: projectHunter

        - name: Navigate to backend directory
          run: cd projectHunter/backend

        - name: Set up Node.js v19
          uses: actions/setup-node@v3
          with:
            node-version: 19
        
        - name: Install dependencies
          run: npm ci
          working-directory: projectHunter/backend

        - name: Set up environment variables
          run: echo "$(cat secrets.env)" >> $GITHUB_ENV
          working-directory: projectHunter/backend

        - name: Run tests
          run: npm run test
          working-directory: projectHunter/backend

    deploy-backend:
        runs-on: ubuntu-latest
        needs: build-backend

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build and push Docker image
          run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t zirolet/multi-backend:latest -t zirolet/multi-backend:$GITHUB_SHA .
            docker push zirolet/multi-backend
          working-directory: projectHunter/backend
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}